import { ICalls } from "@/api/calls/interfaces";

export const faker: ICalls = {
  total_rows: "408",
  results: [
    {
      id: 10385561,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 16:19:04",
      date_notime: "2024-09-19",
      time: 5,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "791**08**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384846,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:51:50",
      date_notime: "2024-09-19",
      time: 9,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "791**08**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384844,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:50:29",
      date_notime: "2024-09-19",
      time: 63,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**85**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384741,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:50:18",
      date_notime: "2024-09-19",
      time: 9,
      from_number: "sip**ha**",
      from_extension: "103",
      to_number: "791**08**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 3487,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384740,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:49:27",
      date_notime: "2024-09-19",
      time: 16,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**13**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384685,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:49:00",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**69**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384683,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:48:39",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "791**45**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384681,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:48:17",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**73**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384677,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:47:19",
      date_notime: "2024-09-19",
      time: 4,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "798**46**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384676,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:46:42",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**68**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384541,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:46:14",
      date_notime: "2024-09-19",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**13**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384540,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:45:58",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "797**03**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384501,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:44:33",
      date_notime: "2024-09-19",
      time: 6,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "791**35**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384500,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:43:49",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**90**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384453,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:42:50",
      date_notime: "2024-09-19",
      time: 6,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "791**16**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384293,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:36:48",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**94**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384233,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:36:07",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**17**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384232,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:35:11",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**89**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384190,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:35:01",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**97**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384189,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:34:12",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**80**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384188,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:33:27",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**79**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384131,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:32:45",
      date_notime: "2024-09-19",
      time: 12,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**55**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384130,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:32:00",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**20**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384058,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:31:25",
      date_notime: "2024-09-19",
      time: 4,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "798**49**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384057,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:31:12",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**49**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384056,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:30:26",
      date_notime: "2024-09-19",
      time: 4,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "798**43**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384048,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:29:58",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**67**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10384047,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:29:28",
      date_notime: "2024-09-19",
      time: 4,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**55**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10383963,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:25:29",
      date_notime: "2024-09-19",
      time: 96,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**88**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10383891,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 15:24:26",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**93**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10380279,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 13:09:55",
      date_notime: "2024-09-19",
      time: 7,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "798**18**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10380278,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 13:09:01",
      date_notime: "2024-09-19",
      time: 9,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**20**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10380109,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 13:03:08",
      date_notime: "2024-09-19",
      time: 141,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**19**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10380006,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 13:02:33",
      date_notime: "2024-09-19",
      time: 7,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**81**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379965,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 13:01:27",
      date_notime: "2024-09-19",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**74**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379962,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 13:00:51",
      date_notime: "2024-09-19",
      time: 5,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**85**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 1,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379769,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:56:10",
      date_notime: "2024-09-19",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**68**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379768,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:55:00",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "791**60**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379732,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:54:19",
      date_notime: "2024-09-19",
      time: 16,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "799**76**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379691,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:53:09",
      date_notime: "2024-09-19",
      time: 4,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**98**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379690,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:52:43",
      date_notime: "2024-09-19",
      time: 8,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "793**56**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "MToxMDA2NzYxNToxNDMwMDM3NzExNzow",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379689,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:52:12",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**49**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379645,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:51:46",
      date_notime: "2024-09-19",
      time: 2,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**44**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379644,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:51:12",
      date_notime: "2024-09-19",
      time: 4,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "790**19**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10379643,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:50:24",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "795**54**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10378672,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:01:40",
      date_notime: "2024-09-19",
      time: 3,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**66**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10378671,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:00:45",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "796**93**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10378657,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 12:00:31",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "792**04**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10378656,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 11:59:52",
      date_notime: "2024-09-19",
      time: 4,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "791**39**",
      to_extension: "",
      is_skilla: 0,
      status: "Дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    },
    {
      id: 10378620,
      partnership_id: "578",
      partner_data: {
        id: "578",
        name: "ООО \"ГРУЗЧИКОВ-СЕРВИС СПБ\"",
        phone: "74951205096"
      },
      date: "2024-09-19 11:58:50",
      date_notime: "2024-09-19",
      time: 0,
      from_number: "sip**r_**",
      from_extension: "671",
      to_number: "793**66**",
      to_extension: "",
      is_skilla: 0,
      status: "Не дозвонился",
      record: "",
      line_number: "sip**se**",
      line_name: "",
      in_out: 0,
      from_site: 0,
      source: "",
      errors: [],
      disconnect_reason: "",
      results: [],
      stages: [],
      abuse: [],
      contact_name: "",
      contact_company: "",
      person_id: 4730,
      person_name: "**",
      person_surname: "**",
      person_avatar: "https://lk.skilla.ru/img/noavatar.jpg",
      candidate_id: 0,
      candidate_name: "",
      candidate_link: "",
      candidate_vacancy_name: ""
    }
  ]
};
